using System;
using System.Globalization;
using System.IO;
using System.Text;
using ArtOfSimRally.Mod;

namespace ArtOfSimRally.Tools
{
    /// <summary>
    /// Emits art of rally's steering force curve as a conformance vector.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The curve is duplicated: it is <see cref="ForceCurve"/> here and
    /// <c>simlite@1</c> in dbce-wheel-mod-toolkit. Nothing enforces that those
    /// agree, and the failure mode is silent - a force that is subtly wrong feels
    /// like the mod got worse, months after whatever changed.
    /// </para>
    /// <para>
    /// This turns "does it feel the same?" into "is the number the same?". The
    /// grid is swept over the ranges the game actually produces, measured on a
    /// real drive 2026-09-02 and recorded in docs/FORCE-FEEDBACK.md, not over
    /// arbitrary values: lateral force to about 4,400 N per wheel, front slip
    /// angles of 12-29 degrees in ordinary corners against an ideal of 8.5, and
    /// the fade band between 3 and 12 km/h.
    /// </para>
    /// </remarks>
    internal static class Program
    {
        // Defaults as shipped in 0.2.2. FyReference was retuned twice to land
        // here; Strength 50 is gain 1.0, the slider midpoint.
        private const float FyReference = 11500f;
        private const float Gain = 1.0f;

        private static int Main(string[] args)
        {
            string outPath = args.Length > 0 ? args[0] : "force-curve-vector.csv";

            // Chosen to straddle every corner in the curve: zero, the fade band
            // edges and midpoint, the ideal slip angle and its double (where the
            // trail reaches its floor), the measured cornering slip angles, and
            // the saturation point where the output clamps.
            float[] fyN = { 0f, 500f, 1500f, 3000f, 5750f, 8000f, 11500f, 14000f, -3000f, -8800f };
            float[] slipDeg = { 0f, 4.25f, 8.5f, 12f, 17f, 21.25f, 29f, 45f };
            float[] speedKmh = { 0f, 3f, 5f, 7.5f, 12f, 40f, 90f, 130f };
            const float idealDeg = 8.5f;

            var sb = new StringBuilder();
            sb.AppendLine("# art of sim rally - steering force curve conformance vector");
            sb.AppendLine("# generated by tools/force-vector from src/ArtOfSimRally.Mod/ForceCurve.cs");
            sb.AppendLine("# mod 0.2.2 defaults: FyReference=" + Fmt(FyReference) +
                          " gain=" + Fmt(Gain) + " (Strength 50) invert=false ideal_deg=" + Fmt(idealDeg));
            sb.AppendLine("# fade " + Fmt(ForceCurve.FadeStartKmh) + "->" + Fmt(ForceCurve.FadeFullKmh) +
                          " km/h (Unity SmoothStep, cubic), trail 1.0 -> " + Fmt(ForceCurve.LimitTrail) +
                          " at twice ideal slip");
            sb.AppendLine("# 'normalised' is pre-smoothing, -1..1. 'device' is (int)(normalised * 10000),");
            sb.AppendLine("# the DirectInput constant-force magnitude actually sent.");
            sb.AppendLine("fy_total_n,abs_slip_deg,ideal_deg,speed_kmh,trail,normalised,device");

            int rows = 0;
            foreach (float fy in fyN)
                foreach (float slip in slipDeg)
                    foreach (float v in speedKmh)
                    {
                        float trail = ForceCurve.Trail(slip, idealDeg);
                        float n = ForceCurve.Normalised(fy, slip, idealDeg, v, FyReference, Gain, false);
                        sb.AppendLine(string.Join(",",
                            Fmt(fy), Fmt(slip), Fmt(idealDeg), Fmt(v),
                            Fmt9(trail), Fmt9(n), ((int)(n * 10000)).ToString(CultureInfo.InvariantCulture)));
                        rows++;
                    }

            // The smoothing filter is stateful, so a grid cannot capture it. A
            // step response pins it exactly: unfiltered, the shipped default, and
            // the 0.50 a user settled on. Note the filter is symmetric - it does
            // not distinguish a rising force from a falling one, which is the
            // most likely point of divergence from an attack/decay pair.
            sb.AppendLine();
            sb.AppendLine("# smoothing step response: target steps 0 -> 1 at step 1, then -> 0 at step 11");
            sb.AppendLine("smoothing,step,target,output");
            foreach (float s in new[] { 0f, 0.2f, 0.5f })
            {
                float prev = 0f;
                for (int step = 0; step <= 20; step++)
                {
                    float target = (step >= 1 && step <= 10) ? 1f : 0f;
                    prev = ForceCurve.Smooth(prev, target, s);
                    sb.AppendLine(string.Join(",", Fmt(s), step.ToString(CultureInfo.InvariantCulture),
                                              Fmt(target), Fmt9(prev)));
                    rows++;
                }
            }

            File.WriteAllText(outPath, sb.ToString());
            Console.WriteLine("wrote " + rows + " rows to " + Path.GetFullPath(outPath));
            return 0;
        }

        // Round-trippable and culture-invariant: this file is compared byte for
        // byte by another repository's test suite.
        private static string Fmt(float v) => v.ToString("0.###", CultureInfo.InvariantCulture);
        private static string Fmt9(float v) => v.ToString("0.#########", CultureInfo.InvariantCulture);
    }
}
