using System;
using GameReaderCommon;
using SimHub.Plugins;

namespace ArtOfSimRally.SimHub
{
    [PluginName("Art of Sim Rally landing haptics")]
    [PluginAuthor("d-b-c-e")]
    [PluginDescription("Dedicated, expiring landing pulse for a SimHub ShakeIt custom effect. No audio is generated by this plugin.")]
    public sealed class ArtOfSimRallyHaptics : IPlugin, IDataPlugin
    {
        private HapticReceiver _receiver;
        private string _status="Not started";
        public PluginManager PluginManager { get; set; }
        public void Init(PluginManager pluginManager)
        {
            PluginManager=pluginManager;
            try { _receiver=new HapticReceiver(); _status="Listening on loopback"; }
            catch(Exception ex) { _status="Unable to listen: "+ex.Message; }
            this.AttachDelegate("LandingPulse",()=>_receiver?.Value ?? 0);
            this.AttachDelegate("Connected",()=>_receiver?.Connected ?? false);
            this.AttachDelegate("AcceptedLandings",()=>_receiver?.Accepted ?? 0);
            this.AttachDelegate("RejectedPackets",()=>_receiver?.Rejected ?? 0);
            this.AttachDelegate("Status",()=>_status);
            global::SimHub.Logging.Current.Info("ArtOfSimRally haptics: "+_status);
        }
        public void DataUpdate(PluginManager pluginManager, ref GameData data) { }
        public void End(PluginManager pluginManager) { _receiver?.Dispose(); _receiver=null; _status="Stopped"; }
    }
}
